#!/bin/bash

# Source config or die
. /etc/linuxmuster-mrbs-manager/config || exit 1


# Passwort erzeugen, wenn nötig
if [ $MRBS_DB_PASS == "GENERATE" ]; then 
	MRBS_DB_PASS=$(pwgen -n 22 1)
	sed -i "s/GENERATE/$MRBS_DB_PASS/" /etc/linuxmuster-mrbs-manager/config
fi

print_help () {
echo "Aufruf:"
echo "  $0 <Instanzname> <DB-Name>"
echo 
echo "Instanzname: Webroot Name, z.B. ka-plan"
echo "  Die mrbs-Instanz steht dann unter https://<server>/ka-plan"
echo "  zur Verfügung"
echo "DB-Name: Name der InstanzDB, ohne Präfix, z.B. kaplan"
echo "  Die mrbs-Instanz verwendet dann die DB ${MRBS_DB_PREFIX}_kaplan"
echo 
exit 0
}

[ "x$1" != "x" ] || print_help;
[ "x$2" != "x" ] || print_help;

# Name der einzurichtenden Instanz: Erstes Argument
MRBS_NAME=$1
# Datenbank für die einzurichtende Instanz
# Zweites Argument
MRBS_DB_NAME=${MRBS_DB_PREFIX}_$2
# Zielverzeichnis für die neue Installation
TARGET_DIR=${MRBS_WEB_BASE}${MRBS_NAME}

if [ -d $TARGET_DIR ]; then 
	echo "Das Verzeichnis $TARGET_DIR"
	echo "existiert bereits."
	print_help
fi

for db in $(echo "show databases;" | mysql | grep $MRBS_DB_PREFIX); do
	if [ $db == $MRBS_DB_NAME ]; then 
		echo "$MRBS_DB_NAME existiert schon"
		print_help
	fi
done



create_fresh_db (){
# Datenbankbenutzer anlegen/Passwort setzen
SQL="grant usage on *.* to ${MRBS_DB_USER}@localhost identified by \"${MRBS_DB_PASS}\";"
SQL=$SQL"create database ${MRBS_DB_NAME};"
SQL=$SQL"GRANT ALL PRIVILEGES ON ${MRBS_DB_NAME}.* TO ${MRBS_DB_USER}@localhost  IDENTIFIED BY \"${MRBS_DB_PASS}\";"
SQL=$SQL"flush privileges;"
mysql -u root << EOMYSQL
$SQL
EOMYSQL
# DB füllen
mysql $MRBS_DB_NAME < "$MRBS_SRC/tables.my.sql"
}

create_new_webroot () {
mkdir -p $MRBS_WEB_BASE
cp -r $MRBS_SRC/web $TARGET_DIR
}

patch_config() {
CFILE="$TARGET_DIR/config.inc.php"
echo $CFILE
sed -i "s/\(\$db_login.*=\s*\).*;/\1\"$MRBS_DB_USER\";/" $CFILE
sed -i "s/\(\$db_password.*=\s*\).*;/\1\"$MRBS_DB_PASS\";/" $CFILE
sed -i "s/\(\$db_database.*=\s*\).*;/\1\"$MRBS_DB_NAME\";/" $CFILE
}

create_new_webroot
create_fresh_db
patch_config

